// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _en = {
  "appbar.title": "PetSoLive",
  "drawer.header": "Menu",
  "home.title": "Home",
  "home.welcome": "Home",
  "home.description": "Find, adopt, and help pets easily.",
  "home.animals_desc": "Discover pets waiting for a loving home.",
  "home.lost_pets_desc": "Help reunite lost pets with their families.",
  "home.help_requests_desc": "Support or request help for pets in need.",
  "home.animals_title": "Explore Pets",
  "home.lost_pets_title": "Lost Pet Ads",
  "home.help_requests_title": "Help Requests",
  "explore.title": "Explore",
  "explore.coming_soon": "Explore coming soon!",
  "profile.title": "Profile",
  "profile.coming_soon": "Profile coming soon!",
  "pet_detail.title": "Pet Detail",
  "pet_detail.adopt": "Adopt Me",
  "pets.title": "Animals",
  "lost_pets_title": "Lost Pets",
  "lost_pets_error": "An error occurred while loading lost pet ads.",
  "lost_pets_empty": "No lost pet ads found.",
  "lost_pets_status_open": "Open",
  "lost_pets_all": "All",
  "lost_pets_search_hint": "Search...",
  "lost_pets_detail_title": "Lost Pet Details",
  "lost_pets_my_ads_only": "My Lost Pet Ads",
  "help_requests.title": "Help Requests",
  "help_requests.empty": "No help requests found.",
  "help_requests.error": "An error occured.",
  "error.occurred": "An error occurred: {0}",
  "login.title": "Login",
  "drawer.website": "Visit Website",
  "theme.switch": "Switch Theme",
  "drawer.change_language": "Change Language",
  "pets.error": "An error occurred while loading pets.",
  "pets.empty": "No pets found.",
  "pets.detail": "Detail",
  "lost_pets.error": "An error occurred while loading lost pet ads.",
  "lost_pets.empty": "No lost pet ads found.",
  "lost_pets.status_open": "Open",
  "animals.title": "Pets",
  "home.featured_pets": "Recently Added Pets",
  "home.help_requests": "Help Requests",
  "profile.login_prompt": "Please log in to view your profile.",
  "profile.logout": "Logout",
  "profile.app_info": "App Information",
  "profile.developer_info": "Developer Info",
  "profile.language": "Language",
  "profile.change_language": "Change Language",
  "profile.supported_languages": "Supported Languages",
  "app_name": "PetSoLive",
  "developer_name": "BulutSoft",
  "support_email": "petsolivesoft@gmail.com",
  "official_website": "www.petsolive.com.tr",
  "about_app_title": "About the App",
  "about_app_description": "PetSoLive is a modern platform to help, find, and adopt pets. Developed with love by BulutSoft.",
  "send_notification": "Send Notification",
  "notification_sent": "Notification sent!",
  "privacy_policy": "Privacy Policy",
  "terms_of_service": "Terms of Service",
  "coming_soon": "Coming soon!",
  "rate_us": "Rate Us",
  "all_rights_reserved": "© BulutSoft. All rights reserved.",
  "login_title": "Login",
  "profile_login_prompt": "Please log in to view your profile.",
  "more_from_bulutsoft": "More from BulutSoft",
  "bulutsoft_description": "BulutSoft is an independent app developer organization.",
  "pets.add": "Add Pet",
  "pets.waiting": "Waiting",
  "pets.adopted": "Adopted",
  "pets.search_hint": "Search...",
  "pets.owned": "Owned",
  "pets.count": "pets",
  "pets.filter_all": "All",
  "pets.filter_species": "Species",
  "pets.filter_color": "Color",
  "pets.filter_breed": "Breed",
  "pets.title_waiting": "Adoptable Pets",
  "pets.title_owned": "Owned Pets",
  "pets.title_all": "All Pets",
  "pets.page_description": "On this page, you can see adoptable pets and use filters and search for detailed results.",
  "pets.info_title": "Page Info",
  "pets.info_description": "On this page, you can see adoptable, owned, and waiting pets, and use filters and search for detailed results.",
  "pets.simple_count": "items listed",
  "pet_detail.species": "Species",
  "pet_detail.breed": "Breed",
  "pet_detail.age": "Age",
  "pet_detail.gender": "Gender",
  "pet_detail.weight": "Weight",
  "pet_detail.color": "Color",
  "pet_detail.date_of_birth": "Date of Birth",
  "pet_detail.vaccination_status": "Vaccination Status",
  "pet_detail.microchip_id": "Microchip ID",
  "pet_detail.is_neutered": "Neutered",
  "pet_detail.yes": "Yes",
  "pet_detail.no": "No",
  "pet_detail.owner": "Owner",
  "pet_detail.status_owned": "Owned",
  "pet_detail.status_waiting": "Waiting",
  "pet_detail.description": "Description",
  "pet_detail.owner_error": "An error occurred while loading the owner information.",
  "pet_detail.owner_info": "Owner Information",
  "pet_detail.owner_name": "Owner Name",
  "pet_detail.ownership_date": "Ownership Date",
  "pet_detail.adoption_info": "Adoption Information",
  "pet_detail.adopted_by": "Adopted By",
  "pet_detail.adoption_date": "Adoption Date",
  "pet_detail.adoption_status": "Adoption Status",
  "pet_detail.not_adopted": "Not Adopted",
  "pet_detail.previous_owner": "Previous Owner",
  "pet_detail.previous_owner_explanation": "This person was the previous owner before adoption.",
  "pet_detail.adopted_by_info": "Adopted By",
  "pet_detail.adopted_explanation": "This pet has been adopted.",
  "pet_detail.not_adopted_explanation": "This pet has not been adopted yet.",
  "pet_detail.owner_info_waiting": "Owner (Waiting)",
  "pet_detail.waiting_explanation": "This pet is waiting to be adopted.",
  "pet_detail.current_owner": "Current Owner",
  "pet_detail.username": "Username",
  "pet_detail.edit": "Edit",
  "pet_detail.delete": "Delete",
  "pet_detail.delete_confirm_desc": "This action cannot be undone. Are you sure you want to delete this pet?",
  "pet_detail.delete_success": "Pet deleted successfully.",
  "ownership_card": {
    "app_name": "PETSOLIVE",
    "card_title": "USER CARD",
    "adoption_date": "Adoption Date",
    "ownership_date": "Ownership Date",
    "username": "Username",
    "waiting_explanation": "This pet is waiting to be adopted.",
    "adopted_explanation": "This pet has been adopted."
  },
  "adoption_requests_title": "Adoption Requests",
  "adoption_requests_desc": "You can see all adoption requests for this pet in this section.",
  "adoption_requests_empty": "There are no adoption requests for this pet yet.",
  "adoption_requests_error": "An error occurred while loading adoption requests.",
  "adoption_requests_tab_all": "All",
  "adoption_requests_tab_approved": "Approved",
  "adoption_requests_tab_pending": "Pending",
  "adoption_requests_tab_rejected": "Rejected",
  "adoption_request_status_pending": "Pending",
  "adoption_request_status_approved": "Approved",
  "adoption_request_status_rejected": "Rejected",
  "adoption_requests_loaded_count": "requests loaded",
  "lost_pets_city": "City",
  "lost_pets_district": "District",
  "pet_detail_search_comments": "Search in comments...",
  "lost_pets.detail_title": "Lost Pet Details",
  "no_owner_title": "No Owner Yet",
  "no_owner_desc": "This pet does not have an owner yet. You can be the first to adopt!",
  "lost_pet_ad": {
    "description": "Description",
    "details": "Details",
    "location": "Location",
    "last_seen_date": "Last Seen Date",
    "created_at": "Ad Created At",
    "owner_title": "Ad Owner",
    "owner_error": "Failed to load user info",
    "email": "Email",
    "phone": "Phone",
    "address": "Address",
    "city": "City",
    "district": "District",
    "roles": "Roles",
    "verified": "Verified",
    "add_title": "Add Lost Pet Ad",
    "edit_title": "Edit Lost Pet Ad",
    "add_success": "Lost pet ad added successfully.",
    "edit_success": "Lost pet ad updated successfully.",
    "form_pet_info": "Pet Info",
    "form_last_seen": "Last Seen",
    "form_image": "Image",
    "form_city": "City",
    "form_district": "District",
    "form_date": "Date",
    "form_select_date": "Select Date",
    "form_description": "Description",
    "form_pet_name": "Pet Name",
    "form_image_url": "Image URL",
    "form_required": "Required",
    "form_save": "Save",
    "form_cancel": "Cancel",
    "form_error": "An error occurred: {0}",
    "form_success": "Operation successful.",
    "form_failed": "Operation failed: {0}",
    "form_login_required": "You must be logged in to add an ad.",
    "form_loading": "Loading...",
    "form_delete_confirm": "Are you sure you want to delete this lost pet ad?",
    "form_delete_success": "Lost pet ad deleted successfully.",
    "form_delete_failed": "Failed to delete lost pet ad: {0}",
    "form_edit": "Edit",
    "form_delete": "Delete"
  },
  "home.header_subtitle": "Connect with pets, find the lost, and help each other!",
  "common.see_all": "See All",
  "home": {
    "featured_lost_pets": "Latest Lost Pet Ads",
    "featured_help_requests": "Latest Help Requests"
  },
  "common": {
    "see_all": "See All"
  },
  "help_requests.comments": "Comments",
  "help_requests.add_comment": "Add Comment",
  "help_requests.no_comments": "No comments yet.",
  "help_requests.comments_failed": "Comments failed to load.",
  "help_requests.write_comment": "Write your comment here...",
  "help_requests.detail_title": "Help Request Details",
  "help_requests.tab_all": "All",
  "help_requests.tab_low": "Low",
  "help_requests.tab_medium": "Medium",
  "help_requests.tab_high": "High",
  "help_requests.status_open": "Open",
  "help_requests.status_closed": "Closed",
  "help_requests.emergency_low": "Low",
  "help_requests.emergency_medium": "Medium",
  "help_requests.emergency_high": "High",
  "help_requests.status_active": "Active",
  "help_requests.change_language": "Change Language",
  "profile.account_section": "Account",
  "profile.app_settings": "App Settings",
  "profile.dark_mode": "Dark Mode",
  "profile.support_section": "Support",
  "profile.contact_support": "Contact Support",
  "profile.rate_app": "Rate App",
  "profile.share_app": "Share App",
  "profile.version": "Version",
  "profile.privacy_policy": "Privacy Policy",
  "profile.change_theme": "Change Theme",
  "profile.bulutsoft_desc": "BulutSoft is an independent software company focused on modern, user-friendly apps.",
  "profile.furkan_desc": "Furkan Bulut is the lead developer of PetSoLive.",
  "profile.account_desc": "Your account information is shown here. You can log in or out as needed.",
  "profile.dark_mode_desc": "Switch between light and dark themes for your comfort.",
  "profile.language_desc": "Change the app language.",
  "profile.support_desc": "Contact us for support or feedback.",
  "profile.privacy_policy_desc": "Read our privacy policy for details on data protection.",
  "form.required": "Required",
  "form.save": "Save",
  "form.select": "Select",
  "form.error": "Error: {0}",
  "pets.add_subtitle": "Add your pet to the community and help it find a new home!",
  "pets.name": "Name",
  "pets.species": "Species",
  "pets.species_custom": "Species (type)",
  "pets.breed": "Breed",
  "pets.gender": "Gender",
  "pets.gender_Erkek": "Male",
  "pets.gender_Dişi": "Female",
  "pets.age": "Age",
  "pets.color": "Color",
  "pets.weight": "Weight (kg)",
  "pets.date_of_birth": "Date of Birth",
  "pets.vaccination_status": "Vaccination Status",
  "pets.is_neutered": "Neutered?",
  "pets.microchip_id": "Microchip ID",
  "pets.description": "Description",
  "pets.image_url": "Image URL",
  "pets.add_success": "Pet added successfully!",
  "pets.mine": "My Pets",
  "pets.mine_ribbon": "My Pet",
  "pets.tab_all": "All Pets",
  "pets.tab_owned": "Owned",
  "pets.tab_waiting": "Waiting",
  "pets.tab_my_pets": "My Pets",
  "edit_pet.subtitle": "Update pet information.",
  "edit_pet.success": "Pet updated successfully.",
  "edit_pet.identity": "Identity Information",
  "edit_pet.physical": "Physical Features",
  "edit_pet.health": "Health Information",
  "form.cancel": "Cancel",
  "delete_confirm": {
    "title": "Delete Confirmation",
    "description": "Are you sure you want to delete this item? This action cannot be undone.",
    "confirm": "Delete",
    "icon_warning": "Warning"
  },
  "pet_detail.already_adopted": "This pet has already been adopted.",
  "pet_detail.login_to_adopt": "Login to adopt",
  "pet_detail.already_requested": "You have already requested to adopt this pet.",
  "pet_detail.already_adopted_action_blocked": "This pet has already been adopted",
  "pet_detail.already_adopted_action_blocked_desc": "No further actions can be performed on this pet.",
  "adoption_form.info": "With this form, you apply to adopt the selected pet. Your contact information and message will only be shared with the current owner of the pet. The owner will review your application and may contact you via email or phone. The final decision will be made by the current owner. Please introduce yourself and explain why you want to adopt.",
  "adoption_form.title": "Adoption application for '{0}'",
  "adoption_form.subtitle": "Please fill in your information completely. Required fields are marked with *.",
  "adoption_form.name": "Name",
  "adoption_form.email": "Email",
  "adoption_form.phone": "Phone",
  "adoption_form.address": "Address",
  "adoption_form.birthdate": "Date of Birth",
  "adoption_form.message": "Message (optional)",
  "adoption_form.message_hint": "You can write about yourself and why you want to adopt...",
  "adoption_form.submit": "Submit Application",
  "adoption_form.sending": "Sending...",
  "adoption_form.required_phone": "Phone is required",
  "adoption_form.required_address": "Address is required",
  "adoption_form.required_birthdate": "Date of birth is required",
  "adoption_form.success": "Your adoption request has been submitted successfully! The pet owner may contact you soon."
};
static const Map<String,dynamic> _tr = {
  "appbar.title": "PetSoLive",
  "drawer.header": "Menü",
  "home.title": "Ana Sayfa",
  "home.welcome": "PetSoLive'a Hoşgeldiniz!",
  "home.description": "Evcil hayvanları kolayca bulun, sahiplenin ve yardım edin.",
  "home.animals_desc": "Yeni yuvasını bekleyen hayvanları keşfet.",
  "home.lost_pets_desc": "Kayıp hayvanları aileleriyle buluşturmaya yardım et.",
  "home.help_requests_desc": "Yardıma ihtiyacı olan hayvanlar için destek ol veya yardım iste.",
  "home.animals_title": "Hayvanları Keşfet",
  "home.lost_pets_title": "Kayıp İlanları",
  "home.help_requests_title": "Yardım Talepleri",
  "explore.title": "Keşfet",
  "explore.coming_soon": "Keşfet yakında!",
  "profile.title": "Profil",
  "profile.coming_soon": "Profil yakında!",
  "pet_detail.title": "Evcil Hayvan Detayı",
  "pet_detail.adopt": "Sahiplen",
  "pets.title": "Hayvanlar",
  "help_requests.title": "Yardım Talepleri",
  "help_requests.empty": "Hiç yardım talebi bulunamadı.",
  "help_requests.error": "Hata oluştu.",
  "error.occurred": "Bir hata oluştu: {0}",
  "login.title": "Giriş",
  "drawer.website": "Web Sitesini Ziyaret Et",
  "theme.switch": "Temayı Değiştir",
  "drawer.change_language": "Dili Değiştir",
  "pets.error": "Evcil hayvanlar yüklenirken bir hata oluştu.",
  "pets.empty": "Hiç evcil hayvan bulunamadı.",
  "pets.detail": "Detay",
  "animals.title": "Hayvanlar",
  "home.featured_pets": "En son eklenen hayvanlar",
  "home.help_requests": "Yardım istekleri",
  "profile.login_prompt": "Profilinizi görüntülemek için lütfen giriş yapın.",
  "profile.logout": "Çıkış Yap",
  "profile.app_info": "Uygulama Bilgileri",
  "profile.developer_info": "Geliştirici Bilgileri",
  "profile.language": "Dil",
  "profile.change_language": "Dili Değiştir",
  "profile.supported_languages": "Desteklenen Diller",
  "app_name": "PetSoLive",
  "developer_name": "BulutSoft",
  "support_email": "petsolivesoft@gmail.com",
  "official_website": "www.petsolive.com.tr",
  "about_app_title": "Uygulama Hakkında",
  "about_app_description": "PetSoLive, evcil hayvanlara yardım etmek, bulmak ve sahiplenmek için modern bir platformdur. Sevgiyle BulutSoft tarafından geliştirildi.",
  "send_notification": "Bildirim Gönder",
  "notification_sent": "Bildirim gönderildi!",
  "privacy_policy": "Gizlilik Politikası",
  "terms_of_service": "Hizmet Koşulları",
  "coming_soon": "Yakında!",
  "rate_us": "Bizi Değerlendir",
  "all_rights_reserved": "© BulutSoft. Tüm hakları saklıdır.",
  "login_title": "Giriş",
  "profile_login_prompt": "Profilinizi görüntülemek için lütfen giriş yapın.",
  "more_from_bulutsoft": "BulutSoft'tan daha fazlası",
  "bulutsoft_description": "BulutSoft, bağımsız bir uygulama geliştirici organizasyondur.",
  "pets.add": "Hayvan Ekle",
  "pets.waiting": "Bekliyor",
  "pets.adopted": "Sahiplendirildi",
  "pets.search_hint": "Ara...",
  "pets.owned": "Sahipli",
  "pets.count": "adet",
  "pets.filter_all": "Tümü",
  "pets.filter_species": "Tür",
  "pets.filter_color": "Renk",
  "pets.filter_breed": "Cins",
  "pets.title_waiting": "Sahiplenilebilecek Hayvanlar",
  "pets.title_owned": "Sahipli Hayvanlar",
  "pets.title_all": "Tüm Hayvanlar",
  "pets.page_description": "Bu sayfada sahiplendirilebilecek hayvanları görebilir, filtre ve arama ile detaylı sonuçlara ulaşabilirsiniz.",
  "pets.info_title": "Sayfa Bilgisi",
  "pets.info_description": "Bu sayfada sahiplendirilebilecek, sahipli ve bekleyen hayvanları görebilir, filtre ve arama ile detaylı sonuçlara ulaşabilirsiniz.",
  "pets.simple_count": "veri listeleniyor",
  "pet_detail.species": "Türü",
  "pet_detail.breed": "Cinsi",
  "pet_detail.age": "Yaşı",
  "pet_detail.gender": "Cinsiyeti",
  "pet_detail.weight": "Kilosu",
  "pet_detail.color": "Rengi",
  "pet_detail.date_of_birth": "Doğum Tarihi",
  "pet_detail.vaccination_status": "Aşı Durumu",
  "pet_detail.microchip_id": "Mikroçip No",
  "pet_detail.is_neutered": "Kısırlaştırma",
  "pet_detail.yes": "Evet",
  "pet_detail.no": "Hayır",
  "pet_detail.owner": "Sahibi",
  "pet_detail.status_owned": "Sahipli",
  "pet_detail.status_waiting": "Bekliyor",
  "pet_detail.description": "Açıklama",
  "pet_detail.owner_error": "Sahip bilgisi yüklenirken bir hata oluştu.",
  "pet_detail.owner_info": "Sahip Bilgisi",
  "pet_detail.owner_name": "Sahip Adı",
  "pet_detail.ownership_date": "Sahiplenme Tarihi",
  "pet_detail.adoption_info": "Sahiplendirme Bilgisi",
  "pet_detail.adopted_by": "Sahiplenen Kişi",
  "pet_detail.adoption_date": "Sahiplendirme Tarihi",
  "pet_detail.adoption_status": "Sahiplendirme Durumu",
  "pet_detail.not_adopted": "Sahiplendirilmemiş",
  "pet_detail.previous_owner": "Önceki Sahibi",
  "pet_detail.previous_owner_explanation": "Bu kişi sahiplendirilmeden önceki sahibidir.",
  "pet_detail.adopted_by_info": "Sahiplenen Kişi",
  "pet_detail.adopted_explanation": "Bu hayvan sahiplendirilmiştir.",
  "pet_detail.not_adopted_explanation": "Bu hayvan henüz sahiplendirilmemiştir.",
  "pet_detail.owner_info_waiting": "Sahiplendiren Kişi",
  "pet_detail.waiting_explanation": "Bu hayvan sahiplendirilmeyi bekliyor.",
  "pet_detail.current_owner": "Güncel Sahip",
  "pet_detail.username": "Kullanıcı Adı",
  "pet_detail.edit": "Düzenle",
  "pet_detail.delete": "Sil",
  "pet_detail.delete_confirm_desc": "Bu işlem geri alınamaz. Bu evcil hayvanı silmek istediğinize emin misiniz?",
  "ownership_card": {
    "app_name": "PETSOLIVE",
    "card_title": "KULLANICI KARTI",
    "adoption_date": "Sahiplenme Tarihi",
    "ownership_date": "Sahiplik Tarihi",
    "username": "Kullanıcı Adı",
    "waiting_explanation": "Bu hayvan sahiplendirilmeyi bekliyor.",
    "adopted_explanation": "Bu hayvan sahiplendirildi."
  },
  "adoption_requests_title": "Sahiplenme İstekleri",
  "adoption_requests_desc": "Bu bölümde hayvana yapılan sahiplenme başvurularını görebilirsiniz.",
  "adoption_requests_empty": "Bu hayvan için henüz sahiplenme başvurusu yok.",
  "adoption_requests_error": "Sahiplenme başvuruları yüklenirken hata oluştu.",
  "adoption_requests_tab_all": "Tümü",
  "adoption_requests_tab_approved": "Kabul Edilenler",
  "adoption_requests_tab_pending": "Bekleyenler",
  "adoption_requests_tab_rejected": "Reddedilenler",
  "adoption_request_status_pending": "Beklemede",
  "adoption_request_status_approved": "Kabul Edildi",
  "adoption_request_status_rejected": "Reddedildi",
  "adoption_requests_loaded_count": "başvuru listelendi",
  "lost_pets_title": "Kayıp İlanları",
  "lost_pets_error": "Kayıp ilanları yüklenirken bir hata oluştu.",
  "lost_pets_empty": "Hiç kayıp ilanı bulunamadı.",
  "lost_pets_status_open": "Açık",
  "lost_pets_city": "Şehir",
  "lost_pets_district": "İlçe",
  "lost_pets_all": "Tümü",
  "lost_pets_search_hint": "Ara...",
  "lost_pets_detail_title": "Kayıp İlanı Detayı",
  "lost_pets_my_ads_only": "Sadece Benim Kayıp İlanlarım",
  "pet_detail_search_comments": "Yorumlarda ara...",
  "no_owner_title": "Sahibi Yok",
  "no_owner_desc": "Bu petin henüz bir sahibi yok. İlk sahiplenmek isteyen sen olabilirsin!",
  "lost_pet_ad": {
    "description": "Açıklama",
    "details": "Detaylar",
    "location": "Konum",
    "last_seen_date": "Son Görülme Tarihi",
    "created_at": "İlan Tarihi",
    "owner_title": "İlanı Oluşturan Kişi",
    "owner_error": "Kullanıcı bilgisi yüklenemedi",
    "email": "E-posta",
    "phone": "Telefon",
    "address": "Adres",
    "city": "Şehir",
    "district": "İlçe",
    "roles": "Roller",
    "verified": "Doğrulandı",
    "add_title": "Kayıp Hayvan İlanı Ekle",
    "edit_title": "Kayıp Hayvan İlanı Düzenle",
    "add_success": "Kayıp ilanı başarıyla eklendi.",
    "edit_success": "Kayıp ilanı başarıyla güncellendi.",
    "form_pet_info": "Hayvan Bilgileri",
    "form_last_seen": "Son Görülme",
    "form_image": "Görsel",
    "form_city": "Şehir",
    "form_district": "İlçe",
    "form_date": "Tarih",
    "form_select_date": "Tarih seç",
    "form_description": "Açıklama",
    "form_pet_name": "Hayvan Adı",
    "form_image_url": "Resim URL",
    "form_required": "Zorunlu",
    "form_save": "Kaydet",
    "form_cancel": "Vazgeç",
    "form_error": "Bir hata oluştu: {0}",
    "form_success": "İşlem başarılı.",
    "form_failed": "İşlem başarısız: {0}",
    "form_login_required": "İlan eklemek için giriş yapmalısınız.",
    "form_loading": "Yükleniyor...",
    "form_delete_confirm": "Bu kayıp ilanını silmek istediğinize emin misiniz?",
    "form_delete_success": "Kayıp ilanı başarıyla silindi.",
    "form_delete_failed": "Kayıp ilanı silinemedi: {0}",
    "form_edit": "Düzenle",
    "form_delete": "Sil"
  },
  "home.header_subtitle": "Evcil dostlarınızı buluşturun, kayıpları bulun, yardımlaşın!",
  "common.see_all": "Tümünü Gör",
  "home": {
    "featured_lost_pets": "En son kayıp ilanları",
    "featured_help_requests": "En son yardım talepleri"
  },
  "common": {
    "see_all": "Tümünü Gör"
  },
  "help_requests.comments": "Yorumlar",
  "help_requests.add_comment": "Yorum Ekle",
  "help_requests.no_comments": "Henüz yorum yok.",
  "help_requests.comments_failed": "Yorumlar yüklenemedi.",
  "help_requests.write_comment": "Yorumunuzu buraya yazın...",
  "help_requests.detail_title": "Yardım Talebi Detayı",
  "help_requests.tab_all": "Tümü",
  "help_requests.tab_low": "Düşük",
  "help_requests.tab_medium": "Orta",
  "help_requests.tab_high": "Yüksek",
  "help_requests.status_open": "Açık",
  "help_requests.status_closed": "Kapalı",
  "help_requests.emergency_low": "Düşük",
  "help_requests.emergency_medium": "Orta",
  "help_requests.emergency_high": "Yüksek",
  "help_requests.status_active": "Aktif",
  "help_requests.change_language": "Dili Değiştir",
  "profile.account_section": "Hesap",
  "profile.app_settings": "Uygulama Ayarları",
  "profile.dark_mode": "Karanlık Mod",
  "profile.support_section": "Destek",
  "profile.contact_support": "Destek ile İletişim",
  "profile.rate_app": "Uygulamayı Değerlendir",
  "profile.share_app": "Uygulamayı Paylaş",
  "profile.version": "Sürüm",
  "profile.privacy_policy": "Gizlilik Politikası",
  "profile.change_theme": "Temayı Değiştir",
  "profile.bulutsoft_desc": "BulutSoft, modern ve kullanıcı dostu uygulamalara odaklanan bağımsız bir yazılım şirketidir.",
  "profile.furkan_desc": "Furkan Bulut, PetSoLive'ın baş geliştiricisidir.",
  "profile.account_desc": "Hesap bilgileriniz burada görüntülenir. Giriş yapabilir veya çıkış yapabilirsiniz.",
  "profile.dark_mode_desc": "Göz konforunuz için açık ve koyu tema arasında geçiş yapın.",
  "profile.language_desc": "Uygulama dilini değiştirin.",
  "profile.support_desc": "Destek veya geri bildirim için bizimle iletişime geçin.",
  "profile.privacy_policy_desc": "Veri koruma detayları için gizlilik politikamızı okuyun.",
  "form.required": "Zorunlu",
  "form.save": "Kaydet",
  "form.select": "Seçiniz",
  "form.error": "Hata: {0}",
  "pets.add_subtitle": "Evcil hayvanını topluluğa ekle ve ona yeni bir yuva bul!",
  "pets.name": "Adı",
  "pets.species": "Türü",
  "pets.species_custom": "Türü (yazınız)",
  "pets.breed": "Cinsi",
  "pets.gender": "Cinsiyeti",
  "pets.gender_Erkek": "Erkek",
  "pets.gender_Dişi": "Dişi",
  "pets.age": "Yaşı",
  "pets.color": "Rengi",
  "pets.weight": "Ağırlığı (kg)",
  "pets.date_of_birth": "Doğum Tarihi",
  "pets.vaccination_status": "Aşı Durumu",
  "pets.is_neutered": "Kısır mı?",
  "pets.microchip_id": "Mikroçip ID",
  "pets.description": "Açıklama",
  "pets.image_url": "Görsel URL",
  "pets.add_success": "Hayvan başarıyla eklendi!",
  "pets.mine": "Hayvanlarım",
  "pets.mine_ribbon": "Benim Hayvanım",
  "pets.tab_all": "Tüm Hayvanlar",
  "pets.tab_owned": "Sahipli",
  "pets.tab_waiting": "Bekliyor",
  "pets.tab_my_pets": "Hayvanlarım",
  "edit_pet.subtitle": "Evcil hayvan bilgilerini güncelleyin.",
  "edit_pet.success": "Evcil hayvan başarıyla güncellendi.",
  "edit_pet.identity": "Kimlik Bilgileri",
  "edit_pet.physical": "Fiziksel Özellikler",
  "edit_pet.health": "Sağlık Bilgileri",
  "form.cancel": "İptal",
  "delete_confirm": {
    "title": "Silme Onayı",
    "description": "Bu öğeyi silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
    "confirm": "Sil",
    "icon_warning": "Uyarı"
  },
  "pet_detail.delete_success": "Pet başarıyla silindi.",
  "pet_detail.already_adopted": "Bu hayvan zaten sahiplendirildi.",
  "pet_detail.login_to_adopt": "Sahiplenmek için giriş yap",
  "pet_detail.already_requested": "Bu hayvan için zaten başvuru yaptınız.",
  "pet_detail.already_adopted_action_blocked": "Bu hayvan zaten sahiplendirildi",
  "pet_detail.already_adopted_action_blocked_desc": "Bu hayvan üzerinde başka bir işlem yapılamaz.",
  "adoption_form.info": "Bu form ile seçtiğiniz hayvanı sahiplenmek için başvuruda bulunursunuz. Girdiğiniz iletişim bilgileri ve mesajınız sadece hayvanın mevcut sahibine iletilir. Hayvan sahibi, başvurunuzu ve iletişim bilgilerinizi inceleyerek sizinle e-posta veya telefon yoluyla iletişime geçebilir. Son karar, hayvanın mevcut sahibi tarafından verilecektir. Lütfen kendinizi ve neden sahiplenmek istediğinizi açıklamayı unutmayın.",
  "adoption_form.title": "'{0}' için sahiplenme başvurusu",
  "adoption_form.subtitle": "Lütfen bilgilerinizi eksiksiz doldurun. Zorunlu alanlar * ile işaretlidir.",
  "adoption_form.name": "Adı",
  "adoption_form.email": "E-posta",
  "adoption_form.phone": "Telefon",
  "adoption_form.address": "Adres",
  "adoption_form.birthdate": "Doğum Tarihi",
  "adoption_form.message": "Mesaj (isteğe bağlı)",
  "adoption_form.message_hint": "Kendinizi ve neden sahiplenmek istediğinizi yazabilirsiniz...",
  "adoption_form.submit": "Başvuruyu Gönder",
  "adoption_form.sending": "Gönderiliyor...",
  "adoption_form.required_phone": "Telefon zorunlu",
  "adoption_form.required_address": "Adres zorunlu",
  "adoption_form.required_birthdate": "Doğum tarihi zorunlu",
  "adoption_form.success": "Sahiplenme başvurunuz başarıyla iletildi! Hayvan sahibi sizinle iletişime geçebilir.",
  "my_ads_only": "Sadece Benim Kayıp İlanlarım"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": _en, "tr": _tr};
}
